ALTER TABLE "ProjectFile"
ADD COLUMN "folder" TEXT NOT NULL DEFAULT 'documents',
ADD COLUMN "viewerIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "editorIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
